добавил бэк и прототип регистрации
Valetron/not_a_hackaton pull request #2
Opened 2023-11-13 16:24 UTC by Worldival

2023-11-13 17:17 UTC, myaak requested changes

2023-11-13 17:17 UTC, myaak commented on backend/src/main/java/com/backend/domain/Student.java
> +
Тут преттиер не настроен

2023-11-13 17:17 UTC, myaak commented on backend/src/main/java/com/backend/domain/Student.java
> +    private String title_group;
так camelCase или snakeCase?
```suggestion
    private Long chatId;
    private String username;
    private String firstname;
    private String middlename;
    private String surname;
    private String university;
    private String titleGroup;
```

2023-11-13 17:17 UTC, myaak commented on backend/src/main/java/com/backend/domain/Student.java
> +
UPD: дальше - тоже. Пройдись по всему проекту, отформатируй код. Куча проблов и пустых строчек

2023-11-14 19:54 UTC, myaak requested changes

2023-11-14 19:54 UTC, myaak commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +    private enum StatusBot {
я бы enum вынес куда-то

2023-11-14 19:54 UTC, myaak commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +
тут пробел хз
UPD: и  не только тут

2023-11-14 19:54 UTC, myaak commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +                    e.printStackTrace();
Об этом пользак узнает? Что у тебя ошибка или нет

2023-11-14 19:54 UTC, myaak commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +    private void command(Message message) {
метод назвать нужно с каким-то глаголом

2023-11-14 19:54 UTC, myaak commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +    private List<BotCommand> setMyBotCommand() {
этот метод наверное в инит нужно вынести

2023-11-14 19:54 UTC, myaak commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +        String userName = message.getChat().getUserName();
```suggestion
        String username = message.getChat().getUsername();
```

2023-11-14 19:54 UTC, myaak commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +    private void registration(Message message) {
```suggestion
    private void registerUser(Message message) {
```

2023-11-14 19:54 UTC, myaak commented on backend/src/main/java/com/backend/BackendApplication.java
почему оно всегда тут пробел оставляет

2023-11-15 09:52 UTC, Worldival commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +                    e.printStackTrace();
в методе saveAccount если ошибка, будет сообщение юзеру об ошибке регистрации

2023-11-15 10:57 UTC, Worldival commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +        String userName = message.getChat().getUserName();
message.getChat().getUserName() это метод библы и его название нельзя поменять

2023-11-18 18:17 UTC, Valetron reviewed
исправляй

2023-11-18 18:17 UTC, Valetron commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +                "Что бы посмотреть свои тесты нажмите /my_test");
"Чтобы" - слитно

2023-11-18 18:17 UTC, Valetron commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +                    "что бы прервать процесс регистрации нажмите /abort");
Снова слитно

2023-11-18 18:17 UTC, Valetron commented on backend/src/main/java/com/backend/bot/TestingBot.java
> +                "Что бы посмотреть команды с которыми я работаю нажмите /help");
И снова

2023-11-18 18:17 UTC, Valetron commented on backend/src/main/resources/application.properties
> +bot.token=6586354534:AAHeeQb6LPecf1a4UqdFV2xz05SscAimsGM
Ты еблан, нас взломали

2023-11-18 18:17 UTC, Valetron commented on backend/src/main/resources/application.properties
> +spring.datasource.password=1
Может оставим по-умолчанию пароль?

2023-11-18 18:26 UTC, Worldival commented on backend/src/main/resources/application.properties
> +spring.datasource.password=1
это какой?

2023-11-19 10:02 UTC, myaak commented on backend/src/main/resources/application.properties
> +spring.datasource.password=1
postgres

2023-11-27 08:25 UTC, merged